accounts/urls.py
from django.urls import path

from accounts import views


urlpatterns = [
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
]

app_name = "accounts"

catalog/urls.py
from django.urls import path
from catalog.views import (
    index,
    DishListView,
    DishCreateView,
    DishUpdateView,
    DishDeleteView,
    DishTypeListView,
    DishTypeCreateView,
    DishTypeUpdateView,
    DishTypeDeleteView,
    CookListView,
    CookCreateView,
    CookUpdateView,
    CookDeleteView,
    about_us_view,
    contacts_view,
)


urlpatterns = [
    path("", index, name="index"),
    path("dish/", DishListView.as_view(), name="dish"),
    path("dish/create/", DishCreateView.as_view(), name="dish-create"),
    path("dish/<int:pk>/update/", DishUpdateView.as_view(), name="dish-update"),
    path("dish/<int:pk>/delete/", DishDeleteView.as_view(), name="dish-delete"),
    path("dish_type/", DishTypeListView.as_view(), name="dish-type"),
    path("dish_type/create/", DishTypeCreateView.as_view(), name="dish-type-create"),
    path(
        "dish_type/<int:pk>/update/",
        DishTypeUpdateView.as_view(),
        name="dish-type-update",
    ),
    path(
        "dish_type/<int:pk>/delete/",
        DishTypeDeleteView.as_view(),
        name="dish-type-delete",
    ),
    path("cook/", CookListView.as_view(), name="cook"),
    path("cook/create/", CookCreateView.as_view(), name="cook-create"),
    path("cook/<int:pk>/update/", CookUpdateView.as_view(), name="cook-update"),
    path("cook/<int:pk>/delete/", CookDeleteView.as_view(), name="cook-delete"),
    path("about_us/", about_us_view, name="about_us"),
    path("contacts/", contacts_view, name="contacts"),
]

app_name = "catalog"

kitchen_distribution/urls.py
from django.contrib import admin
from django.urls import path, include

import catalog


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls", namespace="catalog")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("", catalog.views.index, name="index"),
]

app_name = "admin"

accounts/views.py
from django.contrib.auth import authenticate, login, logout
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse


def login_view(request: HttpRequest) -> None | HttpResponse | HttpResponseRedirect:
    if request.method == "GET":
        return render(request, "accounts/login.html")

    elif request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(request, username=username, password=password)
        print(f"Method: {request.method}")
        print(f"POST data: {request.POST}")
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("catalog:index"))

        error_context = {"error": "Invalid info"}
        return render(request, "accounts/login.html", context=error_context)


def logout_view(request: HttpRequest) -> None | HttpResponse | HttpResponseRedirect:
    logout(request)
    return render(request, "accounts/log_out.html")

templates/accounts/log_out.html
{% extends "base.html" %}
{% block content %}
<br>
<p>Logged out</p>
<a href="{% url 'accounts:login' %}">Click here to log in again</a>
{%  endblock %}

templates/accounts/login.html
{% extends 'base.html' %}

{% block title %}Login - Kitchen Distribution System{% endblock %}

{% block content %}
<div class="container">
<div class="d-flex justify-content-center align-items-center" style="height: 80vh;">
    <div class="col-md-4">
        <div class="card shadow p-4">
            <h3 class="text-center mb-4">Login</h3>
            {% if error %}
              <p style="color: red">{{ error }}</p>
            {% endif %}
            <form action="{% url 'accounts:login' %}" method="POST">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="username" class="form-label">Username</label>
                    <input type="text" name="username" class="form-control" placeholder="Enter your username" required>
                </div>
                <div class="mb-3">
                    <label for="password" class="form-label">Password</label>
                    <input type="password" name="password" class="form-control" id="password" placeholder="Enter your password" required>
                </div>
                <div class="d-grid">
                    <button type="submit" class="btn btn-primary">Login</button>
                </div>
            </form>
            <div class="text-center mt-3">
                <a href="{% url 'accounts:logout' %}">Logout</a>
            </div>
        </div>
    </div>
</div>
</div>
{% endblock %}