catalog/urls.py
from django.urls import path
from catalog.views import (
    index,
    DishListView,
    DishCreateView,
    DishUpdateView,
    DishDeleteView,
    DishTypeListView,
    DishTypeCreateView,
    DishTypeUpdateView,
    DishTypeDeleteView,
    CookListView,
    CookCreateView,
    CookUpdateView,
    CookDeleteView,
    about_us_view,
    contacts_view,
)


urlpatterns = [
    path("", index, name="index"),
    path("dish/", DishListView.as_view(), name="dish"),
    path("dish/create/", DishCreateView.as_view(), name="dish-create"),
    path("dish/<int:pk>/update/", DishUpdateView.as_view(), name="dish-update"),
    path("dish/<int:pk>/delete/", DishDeleteView.as_view(), name="dish-delete"),
    path("dish_type/", DishTypeListView.as_view(), name="dish-type"),
    path("dish_type/create/", DishTypeCreateView.as_view(), name="dish-type-create"),
    path(
        "dish_type/<int:pk>/update/",
        DishTypeUpdateView.as_view(),
        name="dish-type-update",
    ),
    path(
        "dish_type/<int:pk>/delete/",
        DishTypeDeleteView.as_view(),
        name="dish-type-delete",
    ),
    path("cook/", CookListView.as_view(), name="cook"),
    path("cook/create/", CookCreateView.as_view(), name="cook-create"),
    path("cook/<int:pk>/update/", CookUpdateView.as_view(), name="cook-update"),
    path("cook/<int:pk>/delete/", CookDeleteView.as_view(), name="cook-delete"),
    path("about_us/", about_us_view, name="about_us"),
    path("contacts/", contacts_view, name="contacts"),
]

app_name = "catalog"

kitchen_distribution/urls.py
from django.contrib import admin
from django.urls import path, include

import catalog


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls", namespace="catalog")),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("", catalog.views.index, name="index"),
]

app_name = "admin"

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Kitchen Distribution System{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">

    <style>
    .wrapper {
        display: flex;
        flex-direction: column;
        min-height: 100vh;
    }
    </style>

</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="{% url 'catalog:index' %}">Distribution System</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item"><a class="nav-link" href="{% url 'catalog:index' %}">Main page</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'catalog:about_us' %}">About us</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'catalog:contacts' %}">Contacts</a></li>
            </ul>
        </div>
    </div>
</nav>

<div class="wrapper">
<div class="container">
    {% block content %}
    {% endblock %}

    {% block pagination %}
    {% if is_paginated %}
        <div class="d-flex justify-content-center mt-4">
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a href="?page={{ page_obj.previous_page_number }}" class="page-link">Prev</a>
                    </li>
                {% endif %}

                {% for num in page_obj.paginator.page_range %}
                    {% if num == page_obj.number %}
                        <li class="page-item active">
                            <span class="page-link">{{ num }}</span>
                        </li>
                    {% else %}
                        <li class="page-item">
                            <a href="?page={{ num }}" class="page-link">{{ num }}</a>
                        </li>
                    {% endif %}
                {% endfor %}

                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a href="?page={{ page_obj.next_page_number }}" class="page-link">Next</a>
                    </li>
                {% endif %}
            </ul>
        </div>
        {% endif %}
    {% endblock %}
</div>
</div>

<footer class="bg-dark text-white text-center py-3 mt-5">
    © 2025 All rights have been protected.
</footer>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>